fix for issue #72
nimsandu/spicetify-bloom pull request #82
Opened 2022-08-07 12:29 UTC by Astromations

two commits cause I accidentally omitted a line and misnamed the issue.

2022-08-07 12:33 UTC, nimsandu commented
@Astromations Just to clarify your fix ill request @kyrie25 to review this fix ok?

2022-08-07 12:34 UTC, nimsandu commented
@kyrie25 can you share your opinion regarding this pr before merge

2022-08-07 12:39 UTC, kyrie25 commented
> @kyrie25 can you share your opinion regarding this pr before merge 

Have not tested but making the icon disappear doesn't really count as fixing the issue but rather a lazy (no offense) workaround to omit a Spotify feature, of which will raise questions among users.
Would be nice if you can find a way to realign the icons instead.

2022-08-08 05:12 UTC, nimsandu commented
@Astromations Can you work regarding @kyrie25 s review please?

@kyrie25 Thank you for sharing your idea

2022-08-08 05:17 UTC, MGPlayzYT commented
It could be fixed the same way as I did in #71.

2022-08-08 10:52 UTC, Astromations commented
> > @kyrie25 can you share your opinion regarding this pr before merge
> 
> Have not tested but making the icon disappear doesn't really count as fixing the issue but rather a lazy (no offense) workaround to omit a Spotify feature, of which will raise questions among users. Would be nice if you can find a way to realign the icons instead.

If I did keep the icon it'd prevent users from clicking on the center of the playlist.

2022-08-08 10:55 UTC, kyrie25 commented
The icon is marginally small, plus that problem does not arise from the users since it's not the only place they can click to select the playlist.
Removing the feature on the other hand, would arise among users.

2022-08-08 10:57 UTC, MGPlayzYT commented
> > > @kyrie25 can you share your opinion regarding this pr before merge
> > 
> > 
> > Have not tested but making the icon disappear doesn't really count as fixing the issue but rather a lazy (no offense) workaround to omit a Spotify feature, of which will raise questions among users. Would be nice if you can find a way to realign the icons instead.
> 
> If I did keep the icon it'd prevent users from clicking on the center of the playlist.

It's the same case with the playing icon.

2022-08-08 11:15 UTC, Astromations commented
> The icon is marginally small (taking up less than 1/9th of the playlist icon), plus that problem does not arise from the users since it's not the only place they can click to select the playlist. Removing the feature on the other hand, would arise questions among users.

So should I keep the icon and just resize the playlist image

2022-08-08 11:37 UTC, kyrie25 requested changes
This will suffice.

2022-08-08 11:37 UTC, kyrie25 commented on user.css
> +
```suggestion
.main-rootlist-statusIcons > div {
  margin-left: 8px
}

```

2022-08-08 11:56 UTC, Astromations commented
> This will suffice, as it'd only realign the icon and nothing more. Had some free time so I looked into the issue.



> This will suffice, as it'd only realign the icon and nothing more. Had some free time so I looked into the issue.

That works. I'll keep the icon removed on my end though cause I find it kind of ugly 
![image](https://user-images.githubusercontent.com/80211195/183412501-b23b161d-7a7d-4000-b1b7-a202efc46957.png)

2022-08-08 16:01 UTC, nimsandu commented
@kyrie25 @Astromations  so we are ready to marge right?

2022-08-08 16:01 UTC, kyrie25 commented
All good.

2022-08-08 16:04 UTC, nimsandu commented
copy that,
merging now

2022-08-08 16:04 UTC, merged

2022-08-08 16:05 UTC, nimsandu commented
@Astromations @kyrie25 @MGPlayzYT thank you